# ~/.tmuxinator/lasser.yml

name: lasser
root: ~/Code/lasser/src

windows:
  - editor: vi
  - tests: 
      layout: main-vertical
      panes:
        - node:
            - cd node.api
            - NODE_ENV=test nodemon app.js
        - api-tests:
            - cd node.api
            - mocha -R spec -w tests/
        - cli-tests:
            - cd node.cli
            - mocha -R spec -w tests/
  - shell: 
  - dev:
      layout: main-horizontal
      panes:
        - node:
            - node.api
            - NODE_ENV=development nodemon app.js
  - mongo:
      layout: main-vertical
      panes:
        - sleep 10 && mongo
        - mongod -v
        - tail -f /usr/local/var/log/mongodb/mongod.log
