# ~/.tmuxinator/node_dev.yml

name: ruby-lib 
root: .

windows:
  - debug: 
      layout: 6bdc,208x57,0,0[208x44,0,0,0,208x12,0,45,2]
      panes:
        - vi
        - kicker -l 0.332 -e 'rspec'
  - shell: 
