# ~/.tmuxinator/node_dev.yml

name: t4a
root: ~/Code/t4a/src/objc/Tracks4Africa

windows:
  - editor: vi
  - appium:
      layout: main-vertical
      panes:
        - calabash-ios console 
        - DEBUG=1 DEVICE_TARGET='iPad Air (8.3 Simulator)' cucumber
        - cd features && vi
  - shell: 
